services:
  app:
    build: .
    container_name: academic-intelligence
    dns: ["8.8.8.8", "8.8.4.4"]
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_KEY=AIzaSyDZLxTECLnYSVHUv5POQ6ZpwgJpr-sRSds
      - ELEVEN_KEY=sk_c3f288a1f45dcca3463b5963681e605c3775895f4712087b
      - GITHUB_WEBHOOK=CarlosCarlos
    networks:
      - red-h

networks:
  red-h:
    external: true